version: '2'
services:
  # phpfpm - app
  app:
    build:
      context: ./docker/app
      dockerfile: app.dockerfile
    image: localhost:5000/testing_app
    volumes:
      - .:/var/www/html
    networks:
      - laradocker

  #nginx
  web:
    build:
      context: ./docker/app
      dockerfile: web.dockerfile
    image: localhost:5000/testing_web
    volumes:
      - .:/var/www/html
    networks:
      - laradocker
    ports:
      - 80:80

  # redis
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    networks:
      - laradocker

networks:
  laradocker:
    driver: "bridge"

volumes:
  redisdata:
    driver: "local"
    